### PR TITLE
Make digitalocean v2 api default

### PR DESCRIPTION
**Pull request by h0lyalg0rithm**
API v1 is at eol.More information here
https://developers.digitalocean.com/documentation/v1/ 

closes fog/fog#3782

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@h0lyalg0rithm What if you just check for `v1` instead and anything else falls in `v2`?
This would count '' as `v2` as well.

**Comment by petems** [comment]
@plribeiro3000 Would an idea to add deprecation warning or even a full error when someone is using `v1`, as it literally won't work anymore, would be good to explain that. Otherwise someone using some old code they found will get a bunch of unexplained errors.

**Comment by plribeiro3000** [comment]
@petems I didn't quite get what you mean.

But my point is that we should have warnings unless the user is using `v2`. Otherwise it will just stop working as soon as `v1` goes down. Anything but `v2` should have warning logs.

**Comment by petems** [comment]
@plribeiro3000 Sorry I explained that badly, looking at the code it already does what I asked :sweat: 

FYI  v1 is already down, was November 9th IIRC: 

```
API v1 has reached end-of-life. All subsequent requests to API v1 will respond with HTTP 410 (Gone) and an error message:
```

**Comment by h0lyalg0rithm** [comment]
@petems I just changed the code to check if the version is 2.
If the user doesnt specify the version number it will use version 2 by default.

**Comment by plribeiro3000** [comment]
@h0lyalg0rithm better i think. Just require the old version if it is `v1`.
I know it wont work but at least it needs to throw a error different of undefined method.

**Comment by geemus** [comment]
Yeah, in addition to a warning, we probably should go ahead and error also to be more explicit.

**Comment by h0lyalg0rithm** [comment]
Thanks for the feedback. I have changed the code to raise an error if they use version v1 for the digitalocean api.

**Comment by geemus** [comment]
Looks good, thanks!

**Comment by h0lyalg0rithm** [comment]
Thanks for accepting the PR

**Comment by plribeiro3000** [comment]
@h0lyalg0rithm Sorry if i missed your PR. We are lucky we have @geemus . =)

Thanks for your efforts!

**Pull request merged**
