### PR TITLE
D.R.Y. out extending and requiring with service wrappers.

### PR DESCRIPTION
**Pull request by cphrmky**

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@cphrmky Thanks! This looks a lot better. Just not sure if thats in the same path @tokengeek is working so i think he is the best to merge this.

cc/ @tokengeek

**Comment by tokengeek** [comment]
I'll hold off until I decide on where the code is going.

Problem with this metaprogramming is that it these files may be the logical places to document how these services are used. Will see how it goes.

**Comment by geemus** [comment]
Sounds good, thanks all, just let me know if there is anything I can help discuss.

**Comment by plribeiro3000** [comment]
Since #113 was closed due a need for rebase i believe this also needs to be closed until its fixed.

**Pull request closed without merging**
