### PR TITLE
use homedirectory, not actual ~ as for cache sandbox.

### PR DESCRIPTION
**Pull request by shaiguitar**
A small followup for caching. Other than this #204 seems to be smooth for various different resources. 

/cc @icco @plribeiro3000

### CODE REVIEW

**Comment by plribeiro3000** [comment]
:+1:

**Comment by geemus** [comment]
Glad to hear it is working well, thanks!

P.S. @shaiguitar does this need a release soon?

**Comment by shaiguitar** [comment]
A release soon would be good. Would be happy to help out with all that if I could.

**Comment by geemus** [comment]
Apologies for delay, v1.44.2 is now out.

**Comment by PikachuEXE** [comment]
Got
```
There was an error while trying to load the gem 'carrierwave'.
There was an error while trying to load the gem 'carrierwave'.
Gem Load Error is: couldn't find HOME environment -- expanding `~'
Backtrace for gem load error is:
/usr/local/lib/ruby/gems/2.3.0/gems/fog-core-1.44.2/lib/fog/core/cache.rb:94:in `expand_path'
/usr/local/lib/ruby/gems/2.3.0/gems/fog-core-1.44.2/lib/fog/core/cache.rb:94:in `<class:Cache>'
/usr/local/lib/ruby/gems/2.3.0/gems/fog-core-1.44.2/lib/fog/core/cache.rb:84:in `<module:Fog>'
/usr/local/lib/ruby/gems/2.3.0/gems/fog-core-1.44.2/lib/fog/core/cache.rb:6:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/fog-core-1.44.2/lib/fog/core/model.rb:2:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/fog-core-1.44.2/lib/fog/core.rb:42:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/fog-aws-1.3.0/lib/fog/aws.rb:1:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/carrierwave-0.11.2/lib/carrierwave/storage.rb:6:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/carrierwave-0.11.2/lib/carrierwave/storage.rb:4:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/carrierwave-0.11.2/lib/carrierwave/storage.rb:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/carrierwave-0.11.2/lib/carrierwave.rb:78:in `<top (required)>'
```
After using new version
I got something wrong?

**Comment by shaiguitar** [comment]
@PikachuEXE try error message says you don't have `$HOME` variable set. Normally this is available in the environment. I pushed a branch at https://github.com/fog/fog-core/compare/master...shaiguitar:home_env_var_empty_use_cwd?expand=1 that can deal with an empty $HOME env var. Otherwise you can just make sure to have it around in the environment.

**Pull request merged**
