### PR TITLE
fix #requires_one

### PR DESCRIPTION
**Pull request by lanej**
* `missing` was not defined

### CODE REVIEW

**Comment by geemus** [comment]
Seems good, unfortunately the 1.8 tests fail. Could you switch the tests to use hash rockets? Thanks!

**Comment by lanej** [comment]
@geemus ah yes. 1.8.

will fix.

**Comment by lanej** [comment]
@geemus good to go. a patch release after would be grand.

**Comment by plribeiro3000** [comment]
Thx @lanej!

**Comment by geemus** [comment]
Thanks!

**Comment by cphrmky** [comment]
@geemus @plribeiro3000 plans to cut a 1.27.3 release with this fix?  I just independently tracked it down, fog-core 1.27.2 has this bug and is breaking the tests in [knife-softlayer](https://github.com/softlayer/knife-softlayer).

**Comment by geemus** [comment]
@cphrmky I didn't have it on my radar to release for this per se, but hoping to release in the next 2-3 days. So hopefully we'll be good here, just have one or two more things in flight still.

**Comment by cphrmky** [comment]
Thx @geemus.

**Comment by geemus** [comment]
Should be available in 1.27.3 of fog-core.

**Comment by cphrmky** [comment]
Excellent!

**Pull request merged**
