### PR TITLE
first pass at making mime/types require optional

### PR DESCRIPTION
**Pull request by geemus**

### CODE REVIEW

**Comment by plribeiro3000** [comment]
:+1:

**Comment by geemus** [comment]
released in 1.35.0

**Comment by heypiotr** [comment]
This broke middleman-s3_sync (version 3.3.4) for me:

```
/usr/local/lib/ruby/gems/2.2.0/gems/fog-core-1.35.0/lib/fog/storage.rb:68:in `get_content_type': uninitialized constant Fog::Storage::MIME (NameError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/fog-core-1.35.0/lib/fog/storage.rb:79:in `parse_data'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fog-aws-0.7.6/lib/fog/aws/requests/storage/put_object.rb:39:in `put_object'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fog-aws-0.7.6/lib/fog/aws/models/storage/file.rb:212:in `save'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fog-core-1.35.0/lib/fog/core/collection.rb:51:in `create'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync/resource.rb:86:in `block in create!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync/resource.rb:126:in `open'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync/resource.rb:126:in `local_content'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync/resource.rb:85:in `create!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync.rb:146:in `block in create_resources'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync.rb:145:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync.rb:145:in `create_resources'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.4/lib/middleman/s3_sync.rb:41:in `sync'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.4/lib/middleman-s3_sync/commands.rb:59:in `s3_sync'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:72:in `method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:20:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/middleman-core-3.4.0/bin/middleman:18:in `<top (required)>'
	from /usr/local/bin/middleman:23:in `load'
	from /usr/local/bin/middleman:23:in `<main>'
```

Explicitly adding `gem 'mime-types'` to my Gemfile fixed the issue.

(I'm on Ruby 2.2.)

**Comment by fredjean** [comment]
Technically, it broke `fog-core` and `fog-aws`... I'm exploring adding mime-types as a dependency of middleman-s3_sync, but I think it is worthwhile to report the issue against fog since it is likely to impact other gems depending on it.

**Comment by plribeiro3000** [comment]
Ouch. Good catch @fredjean. It is a pain but i believe is for the better.
This kind of chain reaction happened before and we had to fix several projects but i think have our hands tied here. Fixing projects that depend on `fog` is much easier then try to push Distros that are LST until 2018 and have ruby `1.9.3` as the stable version.

If you will, could you open an issue at `middleman-s3_sync` and mark me?
Perhaps i can give you a hand fixing it.

Thanks!

**Comment by fredjean** [comment]
We already have an issue to cover this and a new version has been released to include a workaround for this.

**Comment by geemus** [comment]
@fredjean thanks for the heads up. Sorry for the trouble, but glad to hear you have it in hand.

**Pull request merged**
