### PR TITLE
Fix account service to recognize all providers

### PR DESCRIPTION
**Pull request by mfbmina**
I was trying to use Fog::Account on fog-softlayer and I was always getting this message error:
``` softlayer has no account service (ArgumentError) ```

So, when I take a look at this service, I've seen that it always returning this message if provider was different from :stormondemand.

Then, I fixed it!

### CODE REVIEW

**Comment by mfbmina** [comment]
If you can release a new version of fog-core it would be awesome! :smile:

**Comment by plribeiro3000** [comment]
I believe you should do something in the lines of [this](https://github.com/PaeDae/nexus/pull/154) to make it compatible with the 2 supported implementations (`Fog::Account::Provider` and `Fog::Provider::Account`).

**Comment by mfbmina** [comment]
@plribeiro3000 I did what you told me, and I updated all other models too. Hope it useful!

**Comment by geemus** [comment]
Thanks!

**Comment by geemus** [comment]
released v1.31.0

**Comment by plribeiro3000** [comment]
Thanks @mfbmina !

**Comment by mfbmina** [comment]
Thank you guys. I see that you made a fix commit on my PR. What was wrong?

**Comment by geemus** [comment]
@mfbmina ah, there were some tests on fog/fog where it tried to lookup stuff like monitoring for services that don't actually define it (and expect to get a particular error back). Because of the way it was previously written it would just get `undefined method new for nil` instead of the nicer error saying that provider doesn't have that service. Hope that clarifies (basically it was never reaching the else, like it used to).

**Comment by mfbmina** [comment]
Ok @geemus ! I asked just to learn more about fog! :smile:  thank you again!

**Comment by geemus** [comment]
No problem, thanks for your help!

**Pull request merged**
