### PR TITLE
Updating Travis config for <2.0.0 deprecation

### PR DESCRIPTION
**Pull request by Temikus**
See #161 
- Removed <2.0.0 Rubies
- Added Jruby9k (set it to allow failure to see how it works out first)
- Removed 1.8.7 Gemfile

### CODE REVIEW

**Comment by Temikus** [comment]
Build looks OK. 

@plribeiro3000 - Versions look good?

**Comment by plribeiro3000** [comment]
Sure! :heart:

**Comment by plribeiro3000** [comment]
Oh, could you add a notification in `README` like the one we have in the main repo?

https://github.com/fog/fog#ruby-version

**Comment by Temikus** [comment]
@plribeiro3000 :+1: 
Copied the deprecation message into the README.

**Comment by plribeiro3000** [comment]
Ouch. Sorry but you need to add the constraint to the `gemspec` as well. =s

**Comment by Temikus** [comment]
@plribeiro3000 No probs, sure thing. 

Added the following to gemspec:
`spec.required_ruby_version = '>= 2.0'`
Correct?

**Comment by plribeiro3000** [comment]
Yep. Sorry for the trouble.

**Comment by geemus** [comment]
Thanks!

**Pull request merged**
