### PR TITLE
Fixed incorrect warning about net-ssh when net-scp is actually missing

### PR DESCRIPTION
**Pull request by PatrickMcAfee**

### CODE REVIEW

**Comment by plribeiro3000** [comment]
:+1:

**Comment by plribeiro3000** [comment]
@PatrickMcAfee Could you add your email to git and github in a way that you can take ownership of this work?

**Comment by PatrickMcAfee** [comment]
Should be better now.  Let me know if there's something else I need to do.

**Comment by plribeiro3000** [comment]
:+1:

**Comment by geemus** [comment]
Thanks!

**Comment by plribeiro3000** [comment]
closes #167

**Pull request merged**
